# Generated by Django 4.0.2 on 2022-02-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Patient ID', max_length=15)),
                ('sex', models.CharField(help_text="Patient's sex", max_length=16)),
                ('primary_site', models.CharField(help_text="Patient's cancer primary site ", max_length=32)),
                ('t_stage', models.CharField(blank=True, help_text="Patient's T-stage", max_length=32, null=True)),
                ('n_stage', models.CharField(blank=True, help_text="Patient's N-stage", max_length=32, null=True)),
                ('m_stage', models.CharField(blank=True, help_text="Patient's M-stage", max_length=32, null=True)),
                ('hpv_status', models.BooleanField(blank=True, help_text="Patient's HPV status", null=True)),
            ],
        ),
    ]
