# Generated by Django 4.0.2 on 2022-02-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_availability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
