# Generated by Django 4.0.2 on 2022-03-06 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_availability', '0002_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='centre_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_availability.centre'),
        ),
    ]
