# Generated by Django 3.2.13 on 2022-05-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_availability', '0006_auto_20220510_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='db_port',
            field=models.CharField(help_text='Database port', max_length=64, null=True),
        ),
    ]
