# Generated by Django 3.2.14 on 2022-07-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_availability', '0007_config_db_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='centres',
        ),
    ]
