# Generated by Django 3.2.14 on 2022-08-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_availability', '0008_remove_config_centres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Feature name', max_length=15)),
                ('type', models.CharField(help_text='Feature type', max_length=12)),
                ('query', models.CharField(help_text='Feature query', max_length=256)),
                ('filter', models.BooleanField(help_text='Feature filter')),
            ],
        ),
    ]
