# Generated by Django 3.2.14 on 2022-08-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_availability', '0009_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='type',
            field=models.CharField(choices=[('continuous', 'CONTINUOUS'), ('categorical', 'CATEGORICAL')], help_text='Feature type', max_length=12),
        ),
    ]
