# Generated by Django 3.2.14 on 2022-09-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_availability', '0013_config_dashboard_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('access_data_availability_dash', '### Access Head and Neck Dashboard ###'), ('admin_access_data_availability_dash', '### Admin Access Head and Neck Dashboard ###')),
            },
        ),
    ]
