# Generated by Django 3.2.14 on 2022-10-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_availability', '0014_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='dashboard_title',
            field=models.CharField(blank=True, help_text='Dashboard title', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='data_store_query',
            field=models.CharField(blank=True, help_text='Feature query', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='db_name',
            field=models.CharField(blank=True, help_text='Database name', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='db_password',
            field=models.CharField(blank=True, help_text='Database password', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='db_port',
            field=models.CharField(blank=True, help_text='Database port', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='db_servername',
            field=models.CharField(blank=True, help_text='Database server name', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='db_username',
            field=models.CharField(blank=True, help_text='Database username', max_length=64, null=True),
        ),
    ]
