# Generated by Django 3.2.14 on 2022-11-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_availability', '0015_auto_20221005_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='url_endpoint',
            field=models.CharField(blank=True, help_text='Dashboard URL endpoint', max_length=16, null=True),
        ),
    ]
