# Generated by Django 3.2.14 on 2023-01-12 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_availability', '0016_config_url_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_availability.config'),
        ),
    ]
